apiVersion: v1
kind: Secret
metadata:
    name: porkbun-credentials
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:f23DqBBR17k4EhFlYeF8oB6Q6cGQPXwYCINEnKtBP186147a6EZS00sIqwolf2tUWaVH+DLHsqyx29J92Bs5uvXmj50=,iv:A7OjFGVyTJJ/XDgTeCvF1nkJ2B5tR6IIfrGZPV4k6jA=,tag:tdJYxZM9A2geaeFe2sG0+w==,type:str]
    secret-key: ENC[AES256_GCM,data:HCSaMBGR7R9FlmaW5D5jhrXUqLS1h/InEDADgKP692FOb4SxnEJDQDt31b/3bovUwem14ceGOnTsl0+06355ZWtCdQ0=,iv:GT9MwpA+aMvJBDaLHoRdfspGj4WkDizF3wK3eXh2w7s=,tag:iiQiJpQ9umbRAq7YPObd/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zwu2zrh0r6scfnr9wn8u7l63apmrqul2ttwup9ayqhpmhcg4kddsrmnrpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxTmtSNTJxOXJtUFF6UStk
            SE9CVms5eVkxMXlXMmU5VnFwcGEvWjI0WVMwCjZyWnQ0TUdhZXlyN2dxdWl1YmZm
            d0xsZVFYV0dicjNyMCtDNFcxVmNOUE0KLS0tIFF6S2JqRTRJVDlucGQ1RTNPZHo2
            dzFGbEU3SXVySmJCODFHUjJXVlNQcEkK3UjTImOZDf0cClOPf6QhkEf+qbVd7jut
            GqFxHztpsLgIKgitpH+BpxLjfZv60yqHJY2+Qdh+hRu+91MHIi5fNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-25T13:27:59Z"
    mac: ENC[AES256_GCM,data:VCMcu7Uw8yjdrgZRyVqqZk2eDohfET/3FZoyYCAjge9TsPP37/nBwRkeChE1dMfaYwJT9cyqoaIcNMrCXVpp8AvbhP6O3kYcdhpjtzbKFKMq4SZ5JbswleBukqdKgS3qFlRMAbVvLyzut0ScX0d/tSdwHpzqLrdanJMIgdi93RE=,iv:60uNbYpQyJMwSBKy9c5IrgYUn5DrEC5b0EzQQNs155o=,tag:fb1etOsKS9r8zAyZ3WqvSg==,type:str]
    pgp: []
    encrypted_regex: ^(api-key|secret-key)$
    version: 3.9.4
