{{ if not .Values.grpc.enabled }}
{{ $ := merge (deepCopy .) (dict "suffix" "-arangodb") }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pawsitively-purrfect.fullname" . }}-arangodb
  labels:
    {{- include "pawsitively-purrfect.labels" $ | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "pawsitively-purrfect.selectorLabels" $ | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "pawsitively-purrfect.selectorLabels" $ | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "pawsitively-purrfect.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.arangodb.image }}"
          env:
            - name: ARANGO_ROOT_PASSWORD
              value: {{ .Values.arangodb.password }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.arangodb.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /_admin/server/availability
              port: {{ .Values.arangodb.port }}
              httpHeaders:
              - name: Authorization
                value: Basic {{ printf "%s:%s" .Values.arangodb.user .Values.arangodb.password | b64enc }}
          readinessProbe:
            httpGet:
              path: /_admin/server/availability
              port: {{ .Values.arangodb.port }}
              httpHeaders:
              - name: Authorization
                value: Basic {{ printf "%s:%s" .Values.arangodb.user .Values.arangodb.password | b64enc }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - mountPath: /var/lib/arangodb3
              name: storage
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "pawsitively-purrfect.fullname" . }}-arangodb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "pawsitively-purrfect.fullname" . }}-arangodb
  namespace: {{ .Release.Namespace }}
spec:
  volumeMode: Filesystem
  storageClassName: {{ .Values.pvc.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pawsitively-purrfect.fullname" . }}-arangodb
  labels:
    {{- include "pawsitively-purrfect.labels" $ | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.arangodb.port }}
      targetPort: {{ .Values.arangodb.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "pawsitively-purrfect.selectorLabels" $ | nindent 4 }}
{{ end }}
