apiVersion: v1
kind: Secret
metadata:
    name: kazi-ancestry-credentials
    namespace: kazi-ancestry
type: Opaque
stringData:
    PGPASSWORD: ENC[AES256_GCM,data:XpXOvmfZaV5ApUw2,iv:lRSdb2iQi3xEkQW9Wz/UCcr6j4ty2N2+yGry45LMnQs=,tag:LFtq/N0NdlD33OALPDXzkQ==,type:str]
    GOOGLE_CLIENT_ID: ENC[AES256_GCM,data:kBjGIzCvnCWJbsuInOriy7GCoYM8q4pxIzfg607K4z1RA9lIcFKd4WVgBrEnmWA1XZcnH91UPqrUWDn3BohHkWG9GSBCJifK,iv:1PaUqlt1En6f69PK+7WgLs+J+oFGuWHkCNP7e1B1SbQ=,tag:uEPGhKOxiIHHCh8PgAFRHQ==,type:str]
    GOOGLE_CLIENT_SECRET: ENC[AES256_GCM,data:lxGFZWbbDuJp85Z8lXsrk7jBzxPo0c0X8ya9v+CAAO1a6UY=,iv:sCZVhh9ltRB/5Ly9mZjMDjB/BMXKqysjAvBy3rwfJLU=,tag:dwPPjb1rAjimcUQVIDcVtQ==,type:str]
    SESSION_SECRET: ENC[AES256_GCM,data:dsTSrPXQB/JonHeriynSvv+bsaeFU4XARX+bZjoJH8LolZn3bcftas9aaTE=,iv:qjr8A+dtYcmclIZekP4Xm5a9fkHXxPTFBQS3xGNk9Dw=,tag:lBA2+14pPsrhdX0Xi1vg3Q==,type:str]
    ADMIN_EMAILS: ENC[AES256_GCM,data:lX+UpqUIZSeMwFqUiLxLd1e6cGRH,iv:Dasfg59DP21oZPYdnCBhLP0rugRYkOg7jOq6jUaO5Zs=,tag:zF9Blw5t5hpyypN87hAYpQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcXJtVGpkTjZRVUdkbE9m
            eWhyMGlDbXVnZWRnNXU0YmkwNzB4Mjh4T1VJCnRLOWg4cXFwUFdEUmxaN2dPcVE0
            SG5FOWtPUWo2eDdlSnFnMEk5MVFOd1UKLS0tIHJKODBRM1E3UE1UNTVoZ3NscjRj
            a2RCcmM3dmd1aGJTelI4cVdsTk5mdzQKlIe5ShlLPJtZmps+togu1DCmigSF7AWK
            R3rid9dIsItFMAaWfc5T/fEMasqTKyMxCD2lIOO+EwTpJeNOcloFyA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zwu2zrh0r6scfnr9wn8u7l63apmrqul2ttwup9ayqhpmhcg4kddsrmnrpy
    encrypted_regex: ^(PGPASSWORD|GOOGLE_CLIENT_ID|GOOGLE_CLIENT_SECRET|SESSION_SECRET|ADMIN_EMAILS)$
    lastmodified: "2026-06-30T19:37:23Z"
    mac: ENC[AES256_GCM,data:tbxSe/h2kEIoB2J7KiVF2ZBp7TknNIf8vP7e3LWRbXC3HeB5ox3h6+lyGKLXt810ReiyjUGn4gtguwLZMBgpQ5TTRBioXdQiBXQ4wHdL0M3Wuvjd4uo3m2q78DXDxr4kkL4okmryabxqEF8hhWTlBugdh5VYJVxc7DqFu4iQQ/o=,iv:Dka+kryoHhvC+pGfWceD/W+zaIRx+apPxV3wGAX4Nuc=,tag:2EEKaIe14PdFkFwQnmDu/A==,type:str]
    version: 3.13.1
